[theme]
base = "light"
font = "noto-sans-jp"
codeFont = "noto-sans-jp"

[[theme.fontFaces]]
family = "noto-sans-jp"
url = "static/NotoSansJP-Thin.ttf"
style = "normal"
weight = 100

[[theme.fontFaces]]
family = "noto-sans-jp"
url = "static/NotoSansJP-ExtraLight.ttf"
style = "normal"
weight = 200

[[theme.fontFaces]]
family = "noto-sans-jp"
url = "static/NotoSansJP-Light.ttf"
style = "normal"
weight = 300

[[theme.fontFaces]]
family = "noto-sans-jp"
url = "static/NotoSansJP-Regular.ttf"
style = "normal"
weight = 400

[[theme.fontFaces]]
family = "noto-sans-jp"
url = "static/NotoSansJP-Medium.ttf"
style = "normal"
weight = 500

[[theme.fontFaces]]
family = "noto-sans-jp"
url = "static/NotoSansJP-SemiBold.ttf"
style = "normal"
weight = 600

[[theme.fontFaces]]
family = "noto-sans-jp"
url = "static/NotoSansJP-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "noto-sans-jp"
url = "static/NotoSansJP-ExtraBold.ttf"
style = "normal"
weight = 800

[[theme.fontFaces]]
family = "noto-sans-jp"
url = "static/NotoSansJP-Black.ttf"
style = "normal"
weight = 900

[server]
enableStaticServing = true
